### ISSUE TITLE
Readme: remove jekyll / add origin

### ISSUE THREAD

**Issue by muescha** [thakkaryash94/gatsby-github-personal-website#1]
1) In your readme you refer to some Jekyll content. But it's not anymore based on Jekyll

2) you should refer to the inspiration repo /GitHub/personal-website as a small credit for the idea / layout etc

**Comment by thakkaryash94** [comment]
yes, thanks for reminding. I literally copy paste the readme from original and forgot to change few stuffs in a hurry. surely will fix it, update the readme and add original repo link as well. BTW, I also informed them about the same. https://github.com/github/personal-website/issues/59
