### ISSUE TITLE
Lots of error when running npm run develop

### ISSUE THREAD

**Issue by just-Bri** [thakkaryash94/gatsby-github-personal-website#5]
Gist of errors here: https://gist.github.com/reifnotreef/d330279be71e6d46bc5bb57d4280067a

**Comment by thakkaryash94** [comment]
Link is showing 404. Can you please write it here.

**Comment by thakkaryash94** [comment]
I have updated the code + dependencies. Can you please check now.

**Comment by thakkaryash94** [comment]
Closing for now. Please reopen if you get any errors
